[package]
name = "advent_of_code_2022"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.12"  # Check https://crates.io/crates/itertools for the latest versionfg
nom = "8.0.0"

[lib]
name = "advent_of_code_2022"
path = "src/lib.rs"
